#!/usr/bin/env bash
# Bash for maximum portability.

DIR="$( cd "$( dirname "$0" )" && pwd )"

command=$1

link () {
    echo "Linking dotfiles..."
    for source in `find $DIR/dotfiles/* -maxdepth 1 -prune`; do
        echo "SOURCE: $source"
        dest="$HOME/.`basename ${source}`"

        if [[ -h $dest ]]; then
            echo "$dest is a symbolic link, overwriting."
            rm "$dest"
        elif [[ -f $dest ]]; then
            echo "$dest exists, moving to $dest.back."
            if [[ -f "$dest.back" ]]; then
                echo "...which also exists. Sigh. Skipping this one, re-run to try again."
                continue
            fi
            mv "$dest" "$dest.back"
        else
            echo "Linking $dest."
        fi

        ln -s $source $dest
    done
}

install () {
    echo "This doesn't work yet, but it will automatically install homebrew and such."
}

# Note that this is a really dumb way to run the command, but I'm lazy. It'll get changed as soon as it annoys me.
$command
