#!/bin/sh
# Requires the following patches:
# https://github.com/Cloudef/bemenu/pull/96
# https://github.com/vivien/i3blocks/pull/415
# https://github.com/swaywm/sway/pull/5046

export BEMENU_OPTS=""

swaymsg bar bar-0 workspace_buttons no
pkill -USR1 -f i3blocks

find \
    /usr/share/applications $HOME/.local/share/applications/ \
    -name '*.desktop' \
    -print0 \
| xargs -0 basename -s .desktop \
| bemenu \
    --prompt='        apps' \
    --fn='Noto Sans Bold 10' \
    --tb=#00000000 --tf=#ffffffff \
    --fb=#00000000 --ff=#ffffffff \
    --nb=#00000000 --nf=#ffffffff \
    --hb=#00000000 --hf=#ffffffff \
    --sb=#00000000 --sf=#ffffffff \
| tail -n1 \
| xargs -I% swaymsg "exec sh -c \"gtk-launch '%' || %\""

swaymsg bar bar-0 workspace_buttons yes
pkill -USR2 -f i3blocks
