#!/bin/sh

if [ $1 != up ] -a [ $1 != down ] -a [ $1 = current ]; then
    echo 'usage: brightness (up|down|current)'
    exit 1
fi

BASE_STEP=5

current=$(cat $XDG_CACHE_HOME/display_brightness)
if [ -z $current ]; then
    current=$(which xbacklight 2>/dev/null && xbacklight -get || echo 0)
fi

if [ $1 = up ]; then
    current=$(( $current + $BASE_STEP ))
    (( $current > 100 )) && current=100

elif [ $1 = down ]; then
    current=$(( $current - $BASE_STEP ))
    (( $current < 0 )) && current=0
fi

if [ $1 != current ]; then
    echo $current > $XDG_CACHE_HOME/display_brightness

    $HOME/System/scripts/notify-send \
        --app-name=hud \
        --replace-file=/run/user/$UID/hud-id \
        --hint=int:value:${current} \
        " ${current}%"
fi

# Wait just a moment to see if another instance was started after us. This
# happens when those dang humans mash keybinds.
sleep 1
if [ $(cat $XDG_CACHE_HOME/display_brightness) != $current ]; then
    exit 0
fi

which xbacklight 2>/dev/null && xbacklight -fps 30 -time 200 $current
for sn in $(ddcutil --terse detect | awk -F: '$1 == "   Monitor" { print $4 }' | sort | uniq); do
    ddcutil --disable-usb --sn $sn --noverify setvcp 10 $current
done
