#!/usr/bin/env bash
pid=$(cat /proc/*/stat 2>/dev/null | awk '{if ($4 == focused_pid) { print $1 }}' focused_pid="$(swaymsg -t get_tree | jq 'recurse(.nodes[]?) | select(.focused).pid')")
directory=$(readlink "/proc/$pid/cwd")
swaymsg "exec 'cd $directory; exec \$term'"
