#!/usr/bin/env bash
# This script wraps fossil to colorize the output!

output=$(fossil "$@")
echo "$output" | sed \
-e "s/EDITED/`printf "\x1b[34m&\x1b[0m"`/" \
-e "s/ADDED/`printf "\x1b[33m&\x1b[0m"`/" \
-e "s/DELETED/`printf "\x1b[31m&\x1b[0m"`/"
