#!/usr/bin/env bash
# This script combines the fossil commands `status` and `extras` to prevent me from forgetting files.

stat=$( fossil-colorized status 2>&1 )
statexit="$?"
if [ "$statexit" -ne 0 ]; then
    echo -n "$stat"
    exit "$statexit"
fi

extras=$(fossil extras)

echo "$stat"
if [ -n "$extras" ]; then
    printf "\n\x1b[31m!! Files not yet added to repository !!\x1b[30;1m\n(Use \`fossil add .\` to add them.)\x1b[0m\n$(printf "$extras" | sed 's/^/    /')\n"
else
    printf "\n\x1b[32m✓ All files in repository\n"
fi
