#!/bin/sh
set -e
set -o pipefail

MPVCTL_SOCKET="${MPVCTL_SOCKET:-$XDG_CACHE_HOME/mpv-socket}"

[[ $1 == "-h" ]] && echo "usage: mpvctl [-g] property [value...]" && exit 0

if [[ $1 == "-h" ]]; then
    echo "usage: mpvctl command [arg...]"
    echo "       mpvctl (-g|-s) property [value...]"
    exit 0
fi

# Rewrite property accessors. These act differently than normal commands, and
# `get` doesn't even exist as a normal command.
case "$1" in
    -g) command="get_property";;
    -s) command="set_property";;
    *) command="$1";;
esac
shift 2>/dev/null || true

echo "$@" \
    | jq --raw-input --compact-output --arg command "$command" 'split(" ") | {"command": ([$command] + .)}' \
    | { [[ -n $MPVCTL_DEBUG ]] && tee /dev/stderr || cat; } \
    | socat - "$MPVCTL_SOCKET" \
    | { [[ -n $MPVCTL_DEBUG ]] && tee /dev/stderr || cat; } \
    | jq --raw-output '(select(has("error") and .error != "success").error + "\n" | halt_error(1)) // select(has("data")).data'
