#!/usr/bin/env zsh

pending=$(checkupdates 2>/dev/null)
[[ -z $pending ]] && exit 0

set -o pipefail

# Print them all out, with rebuilds in grey
printf '%s\n' "${pending[@]}" | awk '{ split($2, old, "-"); split($4, new, "-"); if (old[1] == new[1]) { print "\x1b[38;5;242m" $0 "\x1b[0m" } else { print $0 } }'

pending_names=( $(echo $pending | cut -d' ' -f1) )

ignores=( $(pacman-conf IgnorePkg; pacman -Qm | cut -d' ' -f1; pacman -Slq custom) )

# Calculate the official packages responsible for affecting any ignores or custom
affected=()
for pkg in $ignores; do
    effects=$(echo -n "$(pactree --linear --depth=1 "$pkg" 2>/dev/null | grep -v "^$pkg\$" | grep -f <(printf '^%s$\n' "${pending_names[@]}"))" | tr '\n' ' ')
    if [[ -n $effects ]]; then
        affected+=("$(printf '%s \x1b[38;5;242m(%s)\x1b[0m' "$pkg" "$effects")")
    fi
done

if [[ -n $affected ]]; then
    printf '\nIgnored + custom packages affected by updates:\n'
    printf '%s\n' "${affected[@]}"
fi
