#!/bin/sh -e

if [ "$1" = up ]; then
    pavc up
elif [ "$1" = down ]; then
    pavc down
elif [ "$1" = mute ]; then
    pavc toggle
else
    echo "usage: volume (up|down|mute)"
    exit 1
fi

# Can't pipe, it runs in a subshell…
read volume mute <<EOF
$(pavc)
EOF

if [ -z "$mute" ]; then
    icon=
else
    icon=" "
fi

$HOME/System/scripts/notify-send \
    --app-name=hud \
    --replace-file=$XDG_RUNTIME_DIR/hud-id \
    --hint=int:value:"${volume%%%}" \
    "$icon $volume"
